### ISSUE TITLE
Post-migration cleanup

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/json-rpc-engine#180]
## Tasks

- [x] Transfer open issues from the source repo into the core monorepo using the `Transfer issue` feature.
  - [x] If applicable, rename to include package name to provide better context when encountered in the core monorepo.
- [x] For open PRs in the source repo, lock conversation (with no reason provided), and leave a comment requesting that authors reopen the PR in core with a link pointing to the discussion in the original PR.
```
This library has now been migrated into the [core monorepo](https://github.com/metamask/core/). This PR has been locked and this repo will be archived shortly. Going forward, releases of this library will only include changes made in the core repo.
- Please push this branch to core and open a new PR there.
- Optionally, add a link pointing to the discussion in this PR to provide context.
```
- [x] Leave a note in the source repo's README announcing the migration and pointing to core.
  - [x] https://github.com/MetaMask/json-rpc-engine/pull/182
```markdown
<table><tr><td><p align="center"><b>⚠️ PLEASE READ ⚠️</b></p><p align="center">This package has been migrated to our <a href="https://github.com/MetaMask/core"><code>core</code></a> monorepo, and this repository has been archived. Please note that all future development and feature releases will take place in the <a href="https://github.com/MetaMask/core"><code>core</code></a> repository.</p></td></tr></table>
```
- [ ] Archive the source repo to prevent any changes from being pushed to it going forward.

## References
- See [#1551 (comment)](https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740) for context on the migration process.
- See [#1079 (comment)](https://github.com/MetaMask/core/issues/1079) for context on the migration initiative.
